export const TYPES = {
    PROPERTY_GET_ALL :'PROPERTY_GET_ALL',
    GET_PROPERTY_BY_AMBIENCE: 'GET_PROPERTY_BY_AMBIENCE',
    SAVE_PROPERTY: 'SAVE_PROPERTY',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    CHANGE_PROPERTY: 'CHANGE_PROPERTY',
    RESET_SELECTED: 'RESET_SELECTED',
    FIND_BY_UBICATION:'FIND_BY_UBICATION',
    FILTERED_PROPERTY: 'FILTERED_PROPERTY',
    FIND_BY_TYPE_OPERATION:'FIND_BY_TYPE_OPERATION',
    FIND_BY_QUANTITY:'FIND_BY_QUANTITY',
    SAVE_USER: 'SAVE_USER',
    SAVE_TOKEN: 'SAVE_TOKEN',
}